### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by mimmus** [datacoda/docker-websocket-echo#3]
At the connection using a simple js client:

2017-03-10 14:06:02+0000 [autobahn.twisted.websocket.WebSocketServerFactory] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1067, in doRead
            protocol = self.factory.buildProtocol(self._buildAddr(addr))
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 135, in buildProtocol
            p = self.protocol()
          File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 665, in __init__
            self.is_closed = txaio.create_future()
          File "/usr/local/lib/python2.7/site-packages/txaio/_unframework.py", line 43, in _throw_usage_error
            "To use txaio, you must first select a framework "
        exceptions.RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_asyncio()

**Comment by PaulGWebster** [comment]
`2020-05-25 17:31:20+0000 [autobahn.twisted.websocket.WebSocketServerFactory] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1067, in doRead
            protocol = self.factory.buildProtocol(self._buildAddr(addr))
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 135, in buildProtocol
            p = self.protocol()
          File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 665, in __init__
            self.is_closed = txaio.create_future()
          File "/usr/local/lib/python2.7/site-packages/txaio/_unframework.py", line 43, in _throw_usage_error
            "To use txaio, you must first select a framework "
        exceptions.RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_asyncio()
`

Using: https://www.websocket.org/echo.html as the client

**Comment by datacoda** [comment]
I'm currently not tooled to fix this.  Willing to accept PRs.
